export const linksTypes = {
  CREATE_LINK_REQUEST: 'CREATE_LINK_REQUEST',
  CREATE_LINK_SUCCESS: 'CREATE_LINK_SUCCESS',
  CREATE_LINK_ERROR: 'CREATE_LINK_ERROR',
  GET_ALL_LINKS_REQUEST: 'GET_ALL_LINKS_REQUEST',
  GET_ALL_LINKS_SUCCESS: 'GET_ALL_LINKS_SUCCESS',
  GET_ALL_LINKS_ERROR: 'GET_ALL_LINKS_ERROR',
}
